include: "rules/common.smk"
include: "rules/simulate_misassemblies.smk"
include: "rules/compare_aligners.smk"
include: "rules/check_curated.smk"
include: "rules/compare_hprc.smk"
include: "rules/nonhuman.smk"


outputs = [
    rules.download_all.input,
    rules.sim_all.input,
    rules.aln_cmp_all.input,
    rules.hg002_curated_all.input,
    rules.hprc_all.input,
    rules.nonhuman_all.input,
]


# Data is not downloaded so must manually trigger.
if config.get("assembly_config"):

    include: "rules/compare_assembly.smk"

    outputs.append(rules.cmp_asm_all.input)


rule all:
    input:
        outputs,
