import glob
from os.path import join, dirname, splitext


OUTPUT_DIR = config["output_dir"]
LOG_DIR = config["log_dir"]
BENCHMARK_DIR = config["benchmark_dir"]
NUCFLAG_CONFIG = config["nucflag_config"]
ASM_COLORS = {
    "CHM13v2.0": "red",
    "CHM13_hifiasm_0.25.0": "orange",
    "CHM13_verkko_2.2.1": "blue",
    "CHM13_verkko_2.3": "teal",
}
ASM_CHM13 = config["asm_chm13"]
REF_SM = "CHM13v2.0"


def get_assembly(sm):
    if sm == "CHM13v2.0":
        return ASM_CHM13
    elif sm.split("_")[1] == "verkko":
        return expand(rules.denovo_verkko_output.output, asm=sm.split("_")[1], sm=sm)[0]
    else:
        return expand(rules.denovo_hifiasm_output.output, asm=sm.split("_")[1], sm=sm)[
            0
        ]


module DenovoAssembly:
    snakefile:
        "Snakemake-Assembly/workflow/Snakefile"
    config:
        config


use rule * from DenovoAssembly as denovo_*


NF_SAMPLES = [
    {
        # Must have no underscores.
        # Format: SM_verkko or SM_hifiasm
        "name": f"{sm}_{dtype}",
        "asm_fa": get_assembly(sm),
        "reads": config["samples"][sm]["data"][dtype]["path"],
        "config": NUCFLAG_CONFIG[dtype],
    }
    for sm in config["samples"].keys()
    for dtype in ["hifi", "ont"]
]

NF_SAMPLES.extend(
    (
        {
            "name": f"{REF_SM}_{dtype}",
            "asm_fa": ASM_CHM13,
            # All reads the same.
            "reads": config["samples"]["CHM13_verkko_2.2.1"]["data"][dtype]["path"],
            "config": NUCFLAG_CONFIG[dtype],
        }
        for dtype in ["hifi", "ont"]
    )
)

# Then run NucFlag on each assembly
nf_config = {
    "samples": NF_SAMPLES,
    "output_dir": join(OUTPUT_DIR, "nucflag"),
    "output_plots": False,
    "output_pileup": False,
    "output_ideogram": True,
    "output_breakdown": True,
    "logs_dir": join(LOG_DIR, "nucflag"),
    "benchmarks_dir": join(BENCHMARK_DIR, "nucflag"),
    "threads_aln": 24,
    "mem_aln": "50G",
    "processes_nucflag": 24,
    "threads_nucflag": 12,
    "mem_nucflag": "50G",
    # Filter unmapped, non-primary, and supplementary alignments.
    "samtools_view_flag": 2308,
}


module NucFlagDenovoAsm:
    snakefile:
        "../Snakemake-NucFlag/workflow/Snakefile"
    config:
        nf_config


use rule * from NucFlagDenovoAsm as nf_denovo_*


include: "liftover.smk"
include: "asm_variant_graph.smk"
include: "compare_homopolymers.smk"
include: "draw_ng50.smk"
include: "compare_all.smk"
include: "cenmap.smk"


rule all:
    input:
        rules.denovo_all.input,
        rules.vg_all.input,
        rules.cmp_homopolymers_all.input,
        rules.nf_denovo_nucflag.input,
        rules.draw_ng50.output,
        rules.calculate_stats.output,
        rules.liftover_all.input,
        rules.compare_all.input,
        rules.cenmap_all.input,
