include: "../common.smk"


"""
{
    Literal["output_dir"]: str,
    Literal["logs_dir"]: str,
    Literal["benchmarks_dir"]: str,
    Literal["reference"]: str,
    Literal["samples"]: {
        str: {
            Literal["assembly"]: str,
            Literal["hifi"]: str,
            Literal["config"]: str,
        }
    }
}
"""

OUTPUT_DIR = config["output_dir"]
LOG_DIR = config["logs_dir"]
BENCHMARK_DIR = config["benchmarks_dir"]
DATA = config["samples"]
REFERENCE = config.get("reference", "Col-PEK")
SAMPLES_NO_REF = [sm for sm in DATA.keys() if sm != REFERENCE]
SAMPLES_HIFI = [f"{sm}_hifi" for sm in DATA.keys()]


rule download_data:
    output:
        data=join(OUTPUT_DIR, "data", "{dtype}", "{sm}.fx.gz"),
        idx=join(OUTPUT_DIR, "data", "{dtype}", "{sm}.fx.gz.fai"),
    params:
        url=lambda wc: DATA[wc.sm][wc.dtype],
    log:
        join(LOG_DIR, "download_data_{dtype}_{sm}.log"),
    conda:
        "../../envs/tools.yaml"
    shell:
        """
        for url in {params.url}; do
            wget --no-verbose {params.url} -O - | zcat | bgzip >> {output.data} 2>> {log}
        done
        samtools faidx {output.data}
        """


nf_config = {
    "samples": [
        {
            "name": f"{sm}_{dtype}",
            "asm_fa": expand(rules.download_data.output.data, sm=sm, dtype="assembly")[
                0
            ],
            "reads": expand(rules.download_data.output.data, sm=sm, dtype=dtype),
            **(
                {"config": DATA[sm]["config"]}
                if dtype == "hifi"
                else {"preset": "ont_r9"}
            ),
        }
        for sm in DATA.keys()
        for dtype in ("hifi", "ont")
    ],
    "output_dir": OUTPUT_DIR,
    "output_plots": False,
    "output_pileup": False,
    "output_ideogram": False,
    "logs_dir": LOG_DIR,
    "benchmarks_dir": BENCHMARK_DIR,
    "threads_aln": 12,
    "mem_aln": "50G",
    "processes_nucflag": 12,
    "threads_nucflag": 12,
    "mem_nucflag": "50G",
    # Filter unmapped, non-primary, and supplementary alignments.
    "samtools_view_flag": 2308,
    # Don't use -y as fastq tags have invalid character.
    # Similar to https://github.com/samtools/samtools/issues/2041
    "aligner_opts": "-a --eqx --cs -x lr:hqae -I8g",
    "output_format": "bam",
}


module NucFlagNonhuman:
    snakefile:
        "../Snakemake-NucFlag/workflow/Snakefile"
    config:
        nf_config


use rule * from NucFlagNonhuman


rule calculate_qv:
    input:
        calls=rules.check_asm_nucflag.output.misassemblies,
    output:
        qv=join(
            OUTPUT_DIR,
            "{sm}.qv.bed",
        ),
    conda:
        "../Snakemake-NucFlag/workflow/env/nucflag.yaml"
    shell:
        """
        nucflag qv -i {input.calls} > {output.qv}
        """


saffire_cfg = {
    "ref": {
        REFERENCE: expand(
            rules.download_data.output.data, sm=REFERENCE, dtype="assembly"
        )[0]
    },
    "sm": {
        sm: expand(rules.download_data.output.data, sm=sm, dtype="assembly")[0]
        for sm in SAMPLES_NO_REF
    },
    "temp_dir": join(OUTPUT_DIR, "saffire", "temp"),
    "output_dir": join(OUTPUT_DIR, "saffire"),
    "logs_dir": join(LOG_DIR, "saffire"),
    "benchmarks_dir": join(BENCHMARK_DIR, "saffire"),
    "aln_threads": 8,
    "aln_mem": "20GB",
    "mm2_opts": "-x asm5 --secondary=no -K 8G",
}


module align_asm_to_ref:
    snakefile:
        "../asm-to-reference-alignment/workflow/Snakefile"
    config:
        saffire_cfg


use rule * from align_asm_to_ref as asm_ref_*


rule generate_ideogram_all:
    input:
        bed_cen=[DATA[sm]["bed_centromeres"] for sm in DATA.keys()],
        bed_misassemblies=expand(
            rules.check_asm_nucflag.output.misassemblies, sm=SAMPLES_HIFI
        ),
        fai=[
            expand(rules.download_data.output.data, sm=sm, dtype="assembly")[0]
            + ".fai"
            for sm in DATA.keys()
        ],
    output:
        ideogram=multiext(join(OUTPUT_DIR, "all_ideogram"), ".png", ".pdf"),
    conda:
        "../../envs/tools.yaml"
    params:
        script="workflow/scripts/nonhuman/draw_all_ideogram.py",
        output_prefix=lambda wc, output: splitext(output[0])[0],
    shell:
        """
        python {params.script} \
        -i <(awk -v OFS="\\t" '{{
                # Add label to groupby
                match(FILENAME, "/([^/]*)_hifi_misassemblies.bed", arr);
                print $0, arr[1]
            }}' {input.bed_misassemblies}) \
        -y <(join <(cat {input.bed_cen}) <(cat {input.fai}) | \
        awk -v OFS="\\t" '{{
            len=$3-$2;
            midpt=int($2+(len/2));
            print $1, 0, $2, ".", "gneg";
            print $1, $2, midpt, ".", "acen";
            print $1, midpt, $3, ".", "acen";
            print $1, $3, $4, ".", "gneg"
        }}') \
        -r <(awk -v OFS="\\t" '{{ print $1, "Chromosome "FNR }}' {input.bed_cen}) \
        -o {params.output_prefix}
        """


rule agg_qv_stats_against_reported:
    input:
        bed_qv=expand(rules.calculate_qv.output, sm=SAMPLES_HIFI),
        reported_qv="data/nonhuman/all_qv.tsv",
    output:
        multiext(
            join(
                OUTPUT_DIR,
                "qv_stats_against_reported",
            ),
            ".png",
            ".pdf",
        ),
    conda:
        "../../envs/tools.yaml"
    params:
        script="workflow/scripts/nonhuman/qv_agg_stats.py",
        output_prefix=lambda wc, output: splitext(output[0])[0],
        labels=" ".join(DATA.keys()),
        colors=" ".join(f"'{DATA[sm].get("color")}'" for sm in DATA.keys()),
    shell:
        """
        python {params.script} \
        -i {input.bed_qv} \
        -l {params.labels} \
        -c {params.colors} \
        -r {input.reported_qv} \
        -o {params.output_prefix}
        """


rule create_groups:
    input:
        bed_cen=lambda wc: DATA[wc.sm.split("_")[0]]["bed_centromeres"],
        fai=lambda wc: expand(
            rules.download_data.output.data, sm=wc.sm.split("_")[0], dtype="assembly"
        )[0]
        + ".fai",
    output:
        bed_groups=join(OUTPUT_DIR, "{sm}_groups.bed"),
    conda:
        "../../envs/tools.yaml"
    shell:
        """
        cat <(awk -v OFS="\\t" '{{ print $0, "cen"}}' {input.bed_cen}) \
            <(bedtools subtract \
                -a <(awk -v OFS="\\t" '{{ print $1, 0, $2 }}' {input.fai}) \
                -b {input.bed_cen} | \
              awk -v OFS="\\t" '{{ print $0, "uniq" }}') > {output.bed_groups}
        """


rule status_groups:
    input:
        bed_calls=rules.check_asm_nucflag.output.misassemblies,
        bed_groups=rules.create_groups.output,
    output:
        status_region=join(OUTPUT_DIR, "{sm}_status_regions_{mode}.bed"),
        status_grp=join(OUTPUT_DIR, "{sm}_status_grps_{mode}.bed"),
    conda:
        "../Snakemake-NucFlag/workflow/env/nucflag.yaml"
    shell:
        """
        nucflag status \
        -i {input.bed_calls} \
        -b {input.bed_groups} \
        -g name \
        -m {wildcards.mode} > {output.status_grp}
        nucflag status \
        -i {input.bed_calls} \
        -b {input.bed_groups} \
        -m {wildcards.mode} > {output.status_region}
        """


rule agg_calls_cen:
    input:
        rgns=lambda wc: expand(
            rules.status_groups.output.status_region, sm=SAMPLES_HIFI, mode=wc.mode
        ),
        grps=lambda wc: expand(
            rules.status_groups.output.status_grp, sm=SAMPLES_HIFI, mode=wc.mode
        ),
    output:
        bed_calls_rgns=join(OUTPUT_DIR, "all_groups_status_{mode}_rgns.bed"),
        bed_calls_grps=join(OUTPUT_DIR, "all_groups_status_{mode}_grps.bed"),
    conda:
        "../../envs/tools.yaml"
    shell:
        """
        awk -v OFS="\\t" '{{
            match(FILENAME, "([^/]*?).bed", arr);
            if (NR == 1) {{ print $0, "file" }}
            else if (FNR == 1) {{ next }}
            else {{ print $0, arr[1] }}
        }}' {input.rgns} > {output.bed_calls_rgns}
        awk -v OFS="\\t" '{{
            match(FILENAME, "([^/]*?).bed", arr);
            if (NR == 1) {{ print $0, "file" }}
            else if (FNR == 1) {{ next }}
            else {{ print $0, arr[1] }}
        }}' {input.grps} > {output.bed_calls_grps}
        """


rule plot_agg_calls_cen:
    input:
        bed_calls_grps=rules.agg_calls_cen.output.bed_calls_grps,
        nucflag_colors="config/nucflag_colors.tsv",
    output:
        multiext(join(OUTPUT_DIR, "all_groups_status_{mode}_rgns"), ".pdf", ".png"),
    conda:
        "../../envs/tools.yaml"
    params:
        script="workflow/scripts/nonhuman/draw_stacked_bar_grps.py",
        output_prefix=lambda wc, output: splitext(output[0])[0],
        labels=" ".join(DATA.keys()),
        colors=" ".join(f"'{DATA[sm].get("color")}'" for sm in DATA.keys()),
    shell:
        """
        python {params.script} \
        -i {input.bed_calls_grps} \
        -l {params.labels} \
        -c {params.colors} \
        -o {params.output_prefix} \
        -k {input.nucflag_colors}
        """


rule all:
    input:
        expand(rules.download_data.output, dtype=["assembly", "hifi"], sm=DATA.keys()),
        rules.nucflag.input,
        expand(rules.calculate_qv.output, sm=SAMPLES_HIFI),
        expand(rules.asm_ref_SafFire.output.bed, ref=REFERENCE, sm=SAMPLES_NO_REF),
        rules.generate_ideogram_all.output,
        expand(rules.agg_calls_cen.output, mode=["count", "length"]),
        expand(rules.plot_agg_calls_cen.output, mode=["count"]),
        rules.agg_qv_stats_against_reported.output,
