import argparse
import polars as pl
import matplotlib.pyplot as plt

NUCFLAG_COLS = {
    "column_11": "qchrom",
    "column_12": "qst",
    "column_13": "qend",
    "column_14": "name",
    "column_19": "item_rgb",
    "column_4": "rchrom",
    "column_5": "rst",
    "column_6": "rend",
}
SEDEF_R1_COLS = {
    "column_11": "qchrom",
    "column_12": "qst",
    "column_13": "qend",
    # "column_14": "qchrom2",
    # "column_15": "qst2",
    # "column_16": "qend2",
    "column_44": "identity",
    "column_4": "rchrom",
    "column_5": "rst",
    "column_6": "rend",
    # "column_9": "qstrand",
    # "column_10": "rstrand",
}
SEDEF_R2_COLS = {
    "column_11": "qchrom",
    "column_12": "qst",
    "column_13": "qend",
    # "column_14": "qitv",
    "column_34": "identity",
    "column_19": "item_rgb",
    "column_4": "rchrom",
    "column_5": "rst",
    "column_6": "rend",
    # "column_9": "qstrand",
    # "column_10": "rstrand",
}


# From https://github.com/EichlerLab/sedef_smk/blob/46f009cbe319613cb0d1f9a26393e25bf1f2c309/scripts/sedef_to_bed.py#L31-L46
def get_color(frac_id):
    """
    convert segdup identity to color
    """
    if frac_id >= 0.99:
        return "255,103,0"
    if frac_id >= 0.98:
        return "204,204,0"
    if frac_id >= 0.9:
        mingray = 105
        maxgray = 220
        gray = int(mingray + (maxgray - mingray) * (1 - (frac_id - 0.9) * 10))
        return f"{gray},{gray},{gray}"
    # return purple
    return "147,112,219"


def group_by_minmax_ref_nucflag(df: pl.DataFrame) -> pl.DataFrame:
    """
    Take minimum and maximum coordinates of reference
    """
    return (
        df.group_by(["qchrom", "qst", "qend", "name", "item_rgb", "rchrom"])
        .agg(pl.col("rst").min(), pl.col("rend").max())
        .with_columns(
            st=pl.col("qst") + pl.col("rst"),
            end=pl.col("qend") + pl.col("rst"),
            mtch=pl.col("qchrom").str.extract_groups(r"^(?<sm>.*?)#(?<hap>1|2)#"),
        )
        .unnest("mtch")
        .sort(["rchrom", "hap", "st"])
    )


def group_by_minmax_ref_sedef(df: pl.DataFrame) -> pl.DataFrame:
    return (
        df.group_by(["qchrom", "qst", "qend", "item_rgb", "rchrom"])
        .agg(pl.col("rst").min(), pl.col("rend").max())
        .with_columns(
            st=pl.col("qst") + pl.col("rst"),
            end=pl.col("qend") + pl.col("rst"),
            mtch=pl.col("qchrom").str.extract_groups(r"^(?<sm>.*?)#(?<hap>1|2)#"),
        )
        .unnest("mtch")
        .sort(["rchrom", "hap", "st"])
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--r1_sedef", nargs="+", type=str)
    ap.add_argument("--r2_sedef", nargs="+", type=str)
    ap.add_argument("--r1_nucflag", nargs="+", type=str)
    ap.add_argument("--r2_nucflag", nargs="+", type=str)
    args = ap.parse_args()

    dfs_r1_nucflag = []
    dfs_r2_nucflag = []
    dfs_r1_sedef = []
    dfs_r2_sedef = []

    for file in args.r1_nucflag:
        df_r1_nucflag = (
            pl.read_csv(
                file,
                separator="\t",
                has_header=False,
            )
            .select(NUCFLAG_COLS.keys())
            .rename(NUCFLAG_COLS)
        )
        dfs_r1_nucflag.append(df_r1_nucflag)

    for file in args.r2_nucflag:
        df_r2_nucflag = (
            pl.read_csv(
                file,
                separator="\t",
                has_header=False,
            )
            .select(NUCFLAG_COLS.keys())
            .rename(NUCFLAG_COLS)
        )
        dfs_r2_nucflag.append(df_r2_nucflag)

    for file in args.r1_sedef:
        df_r1_sedef = (
            pl.read_csv(file, separator="\t", has_header=False)
            .select(SEDEF_R1_COLS.keys())
            .rename(SEDEF_R1_COLS)
            # Use same item_rgb as r2 sedef generated by dongahn
            .with_columns(
                item_rgb=pl.col("identity").map_elements(
                    get_color,
                    return_dtype=pl.String,
                )
            )
            .drop("identity")
        )
        dfs_r1_sedef.append(df_r1_sedef)

    for file in args.r2_sedef:
        df_r2_sedef = (
            pl.read_csv(file, separator="\t", has_header=False)
            .select(SEDEF_R2_COLS.keys())
            .rename(SEDEF_R2_COLS)
            .drop("identity")
        )
        dfs_r2_sedef.append(df_r2_sedef)

    df_r1_nucflag = pl.concat(dfs_r1_nucflag).filter(
        pl.col("name").ne(pl.lit("correct"))
    )
    df_r2_nucflag = pl.concat(dfs_r2_nucflag).filter(
        pl.col("name").ne(pl.lit("correct"))
    )
    df_r1_sedef = pl.concat(dfs_r1_sedef)
    df_r2_sedef = pl.concat(dfs_r2_sedef)

    # Take min and max of same interval in case of alignment gap.
    df_nucflag = pl.concat(
        [
            group_by_minmax_ref_nucflag(df_r1_nucflag).with_columns(
                release=pl.lit("R1")
            ),
            group_by_minmax_ref_nucflag(df_r2_nucflag).with_columns(
                release=pl.lit("R2")
            ),
        ]
    )
    df_sedef = pl.concat(
        [
            group_by_minmax_ref_sedef(df_r1_sedef).with_columns(release=pl.lit("R1")),
            group_by_minmax_ref_sedef(df_r2_sedef).with_columns(release=pl.lit("R2")),
        ]
    )

    sm_haps = set(df_nucflag.select("sm", "hap").iter_rows())
    fig, axes = plt.subplots(
        nrows=len(sm_haps), ncols=2, layout="constrained", sharex=True
    )

    for row_offset, df_annot in enumerate((df_sedef, df_nucflag)):
        for row, (sm, hap) in enumerate(sm_haps):
            row = row + row_offset
            for col, release in enumerate(("R1", "R2")):
                df_sm_hap_annot = df_annot.filter(
                    pl.col("sm").eq(pl.lit(sm))
                    & pl.col("hap").eq(pl.lit(hap))
                    & pl.col("release").eq(pl.lit(release))
                )
                # TODO: Update item_rgb and get break coordinates
                print(row, col, df_sm_hap_annot)
                breakpoint()


if __name__ == "__main__":
    raise SystemExit(main())
