samples:
  CHM13_hifiasm_0.25.0:
    threads: 40
    assembler: hifiasm
    version: 0.25.0
    mem: 250GB
    added_args: "-l0"
    data:
      ont:
        path: []
      hifi:
        path: []
  CHM13_verkko_2.2.1:
    threads: 40
    assembler: verkko
    version: 2.2.1
    mem: 250GB
    data:
      ont:
        path: []
      hifi:
        path: []
  CHM13_verkko_2.3:
    threads: 40
    assembler: verkko
    version: "2.3"
    mem: 250GB
    data:
      ont:
        path: []
      hifi:
        path: []
