[general]
log_level = "info"
bp_merge = 5_000
bp_wg_window = 5_000_000
bp_min_aln_length = 1
ignore_boundaries = true

[cov]
n_zscores_high = 4.0
n_zscores_low = 1.0
ratio_collapse = 2.0
ratio_false_dupe = 0.5

[mapq]
n_zscores_low = 1.0
mapq_agg_fn = "Mean"

[mismatch]
n_zscores_high = 3.5
ratio_het = 1.0
rolling_mean_window = 5

[indel]
n_zscores_high = 3.5
min_ins_size = 10
min_del_size = 10
ratio_indel = 1.0

[softclip]
n_zscores_high = 3.5
ratio_softclip = 0.5

[group_by_ani]
window_size = 5_000
min_grp_size = 100_000
min_ident = 80.0

# [repeat]
# check_types = ["Misjoin", "Indel", "FalseDupe"]
# ratio_repeat = 0.5
# bp_extend = 5

[minimum_size]
null = 1
collapse = 1
misjoin = 1
low_quality = 1
false_dupe = 2
softclip = 1
indel = 1
homopolymer = 1
dinucleotide = 1
simple_repeat = 1
other_repeat = 1
scaffold = 1