import polars as pl
from os.path import join, splitext
from collections import defaultdict
from typing import Iterator


OUTPUT_DIR = config["output_dir"]
LOG_DIR = config["logs_dir"]
BENCHMARK_DIR = config["benchmarks_dir"]
# {sample: {dtype: { R1: [], R2: []}}}
DATA = defaultdict(lambda: defaultdict(dict))
RELEASES = ["R1", "R2"]
SM_METADATA = join("data", "compare_hprc", "hprc_metadata.tsv")
# From other part of workflow
ASM_CHM13 = join(OUTPUT_DIR, "..", "assembly", "reference", "chm13v2.0.fa.gz")
BED_CHM13_SMN = join("data", "compare_hprc", "chm13v2.0_smn_1mbp_slop.bed")

with open(config["manifest"]) as fh:
    # Skip header.
    next(fh)
    for line in fh:
        sample, asm_h1, asm_h2, bam, release = line.strip().split(",")
        DATA[sample]["asm"][release] = [asm_h1, asm_h2]
        DATA[sample]["bam"][release] = [bam]


wildcard_constraints:
    sm="|".join(DATA.keys()),
    release="|".join(RELEASES),


rule download_assemblies:
    output:
        asm=join(OUTPUT_DIR, "data", "{sm}_{release}.fa.gz"),
        asm_fai=join(OUTPUT_DIR, "data", "{sm}_{release}.fa.gz.fai"),
    params:
        uris=lambda wc: DATA[wc.sm]["asm"][wc.release],
    conda:
        # TODO: Consolidate envs
        "../../envs/curated.yaml"
    shell:
        """
        for uri in {params.uris}; do
            aws s3 --no-sign-request cp "${{uri}}" - | zcat | bgzip >> {output.asm}
        done
        samtools faidx {output.asm}
        """


rule download_aligned_bams:
    output:
        bam=join(OUTPUT_DIR, "data", "{sm}_{release}.bam"),
        bai=join(OUTPUT_DIR, "data", "{sm}_{release}.bam.bai"),
    params:
        uri=lambda wc: DATA[wc.sm]["bam"][wc.release],
    conda:
        "../../envs/curated.yaml"
    shell:
        """
        aws s3 --no-sign-request cp {params.uri} {output.bam}
        aws s3 --no-sign-request cp {params.uri}.bai {output.bai}
        """


rule calculate_release_ng50:
    input:
        asm=lambda wc: expand(
            rules.download_assemblies.output.asm, sm=DATA.keys(), release=wc.release
        ),
    output:
        stats=join(OUTPUT_DIR, "ng50", "seq_stats_{release}.tsv"),
    params:
        script="workflow/scripts/compare_assembly/seq_stats.py",
    conda:
        "../../envs/curated.yaml"
    shell:
        """
        python {params.script} {input.asm} -r > {output.stats}
        """


rule run_nucflag:
    input:
        bam=rules.download_aligned_bams.output.bam,
        asm=rules.download_assemblies.output.asm,
    output:
        calls=join(
            OUTPUT_DIR,
            "{sm}_{release}.bed",
        ),
    params:
        preset="hifi",
    conda:
        "../Snakemake-NucFlag/workflow/env/nucflag.yaml"
    threads: 12
    resources:
        threads=12,
        mem="50GB",
    log:
        join(LOG_DIR, "run_nucflag_{sm}_{release}.log"),
    benchmark:
        join(BENCHMARK_DIR, "run_nucflag_{sm}_{release}.tsv")
    shell:
        """
        nucflag call \
        -i {input.bam} \
        -f {input.asm} \
        -x {params.preset} \
        -o {output.calls} \
        -t {resources.threads} \
        -p {threads} 2> {log}
        """


rule calculate_qv:
    input:
        calls=rules.run_nucflag.output.calls,
    output:
        qv=join(
            OUTPUT_DIR,
            "{sm}_{release}.qv.bed",
        ),
    conda:
        "../Snakemake-NucFlag/workflow/env/nucflag.yaml"
    shell:
        """
        nucflag qv -i {input.calls} > {output.qv}
        """


# QV scatter plot
rule plot_qv_comparison:
    input:
        qv_r1=expand(
            rules.calculate_qv.output,
            sm=DATA.keys(),
            release="R1",
        ),
        qv_r2=expand(
            rules.calculate_qv.output,
            sm=DATA.keys(),
            release="R2",
        ),
        metadata=SM_METADATA,
    output:
        qv=join(OUTPUT_DIR, "plots", "hprc_qv_comparison_{typ}.tsv"),
        qv_summary=join(OUTPUT_DIR, "plots", "hprc_qv_comparison_{typ}_summary.tsv"),
        peaks=join(OUTPUT_DIR, "plots", "hprc_qv_comparison_{typ}_peaks.tsv"),
        png=join(OUTPUT_DIR, "plots", "hprc_qv_comparison_{typ}.png"),
    params:
        script="workflow/scripts/compare_hprc/plot_qv_compare.py",
        typ="{typ}",
        output_prefix=lambda wc, output: splitext(output.qv)[0],
    conda:
        "../../envs/curated.yaml"
    shell:
        """
        python {params.script} \
        -a <(cat {input.qv_r1}) \
        -b <(cat {input.qv_r2}) \
        -m {input.metadata} \
        -t {params.typ} \
        -o {params.output_prefix}
        """


# Plot error
rule plot_err_comparison:
    input:
        calls_r1=expand(
            rules.run_nucflag.output.calls,
            sm=DATA.keys(),
            release="R1",
        ),
        calls_r2=expand(
            rules.run_nucflag.output.calls,
            sm=DATA.keys(),
            release="R2",
        ),
        metadata=SM_METADATA,
    output:
        png_cmp_sm=multiext(
            join(OUTPUT_DIR, "plots", "hprc_err_comparison"),
            ".png",
            ".pdf",
        ),
        png_diff_by_name=[
            multiext(
                join(OUTPUT_DIR, "plots", f"hprc_err_comparison_{metric}_combined"),
                ".png",
                ".pdf",
            )
            for metric in ("length", "count", "all_length", "all_count")
        ],
        sm_diff=join(OUTPUT_DIR, "plots", "hprc_err_comparison_sm_diff.tsv"),
        name_diff=join(OUTPUT_DIR, "plots", "hprc_err_comparison_name_diff.tsv"),
        sm_name_diff=join(OUTPUT_DIR, "plots", "hprc_err_comparison_sm_name_diff.tsv"),
    params:
        script="workflow/scripts/compare_hprc/plot_err_compare.py",
        output_prefix=lambda wc, output: splitext(output.png_cmp_sm[0])[0],
    conda:
        "../../envs/tools.yaml"
    shell:
        """
        python {params.script} \
        -a <(cat {input.calls_r1}) \
        -b <(cat {input.calls_r2}) \
        -m {input.metadata} \
        -o {params.output_prefix}
        """


include: "smn.smk"
include: "censat.smk"


rule all:
    input:
        expand(rules.download_assemblies.output, sm=DATA.keys(), release=RELEASES),
        expand(rules.download_aligned_bams.output, sm=DATA.keys(), release=RELEASES),
        expand(
            rules.calculate_qv.output,
            sm=DATA.keys(),
            release=RELEASES,
        ),
        expand(rules.calculate_release_ng50.output, release=RELEASES),
        expand(rules.plot_qv_comparison.output, typ=["length", "qv"]),
        rules.plot_err_comparison.output,
        rules.smn_all.input,
        rules.censat_status_all.input,
    default_target: True
